import React, { useState, useEffect } from 'react';
import { 
  Search, LayoutDashboard, Plus, 
  Check, ChevronRight, Loader2, Layers, Menu, X, LogOut, Calendar
} from 'lucide-react';
import { SHEET_CONFIGS, STUDENT_SHEETS, FACULTY_SHEETS, GOOGLE_SHEET_NAME_MAP, PERIOD_OPTIONS, type PeriodOption } from './schema';
import { useAuth } from './contexts/AuthContext';
import LoginPage from './components/LoginPage';


// Map each bi-monthly period to its Google Script URL (user to paste their URLs)
const GOOGLE_SCRIPT_URLS: Record<PeriodOption, string> = {
  "Jan-Feb2026": "https://script.google.com/macros/s/AKfycbzLzrmtJ8AUarYv-GCbUlgqK8sYkgYVL02OdK834Ggg12g3EnM6cF4BcqlVAOd3MJcevQ/exec",
  "Mar-Apr2026": "https://script.google.com/macros/s/AKfycbxq241ry6OTTvMTZu1rKmWsSmCqG6m2oMN_6bYWouGisRsZHbrI4hNMmP5r7tbXKeDf0Q/exec",
  "May-Jun2026": "https://script.google.com/macros/s/AKfycbyIBdOi_9rZtfE4qsLqm2us82doR_a8v2UNt_gwqHKLSDPW2XkblD0Qwh-xl66FM6Ne/exec",
  "Jul-Aug2026": "PASTE_JUL_AUG_URL_HERE",
  "Sep-Oct2026": "PASTE_SEP_OCT_URL_HERE",
  "Nov-Dec2026": "PASTE_NOV_DEC_URL_HERE"
};




const normalizeSheetName = (name: string): string => name.trim().replace(/\s+/g, ' ').toLowerCase();

const resolveGoogleSheetName = (uiSheetName: string): string | null => {
  // Prefer exact match first to preserve the real tab name as-is.
  if (GOOGLE_SHEET_NAME_MAP[uiSheetName]) {
    return GOOGLE_SHEET_NAME_MAP[uiSheetName];
  }

  for (const value of Object.values(GOOGLE_SHEET_NAME_MAP)) {
    if (value === uiSheetName) {
      return value;
    }
  }

  const normalizedInput = normalizeSheetName(uiSheetName);
  for (const [key, value] of Object.entries(GOOGLE_SHEET_NAME_MAP)) {
    if (normalizeSheetName(key) === normalizedInput || normalizeSheetName(value) === normalizedInput) {
      return value;
    }
  }

  return null;
};

export default function App() {
  const { user, role, period, setPeriod, logout, isAuthenticated } = useAuth();
  const [activeSheet, setActiveSheet] = useState<string>("");
  const [searchQuery, setSearchQuery] = useState("");
  const [studentLogs] = useState<Record<string, any>[]>([]);

  const [isSidebarOpen, setIsSidebarOpen] = useState(false);
  const [isSubmitting, setIsSubmitting] = useState(false);

  const getSelectedScriptLink = (): string => {
    if (!period) {
      throw new Error("No reporting period selected.");
    }
    const url = GOOGLE_SCRIPT_URLS[period];
    if (!url || url.startsWith("PASTE_")) {
      throw new Error(`Google Script URL for period ${period} is not configured. Please paste the correct URL in App.tsx.`);
    }
    return url;
  };

  const postRowToSheet = async (uiSheetName: string, rowData: Record<string, any>, submissionPeriod: PeriodOption) => {
    const targetSheetName = resolveGoogleSheetName(uiSheetName);
    if (!targetSheetName) {
      throw new Error(`Google sheet mapping missing for "${uiSheetName}"`);
    }

    const sheetSchema = SHEET_CONFIGS[uiSheetName] || [];
    const values = sheetSchema.map(f => rowData[f.name]);
    const selectedSheetLink = getSelectedScriptLink();

    await fetch(selectedSheetLink, {
      method: "POST",
      mode: "no-cors",
      headers: { "Content-Type": "text/plain" },
      body: JSON.stringify({
        sheetName: targetSheetName,
        uiSheetName,
        period: submissionPeriod,
        data: [values]
      })
    });
  };

  useEffect(() => {
    if (isAuthenticated && role) {
      const visibleSheets = role === 'student' ? STUDENT_SHEETS : FACULTY_SHEETS;
      if (visibleSheets.length > 0 && !activeSheet) {
        setActiveSheet(visibleSheets[0]);
      }
    }
  }, [isAuthenticated, role, activeSheet]);

  const getVisibleSheets = () => {
    if (role === 'student') return STUDENT_SHEETS;
    if (role === 'faculty') return FACULTY_SHEETS;
    return [];
  };

  const appendToDf = async (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    const formData = new FormData(e.currentTarget);
    const formEntries = Object.fromEntries(formData.entries());

    if (role === 'student') {
      const proofFields = (SHEET_CONFIGS[activeSheet] || []).filter((field) =>
        /(proof|doc|link)/i.test(`${field.name} ${field.label}`)
      );

      const missingProofField = proofFields.find((field) => {
        const value = formEntries[field.name];
        return typeof value !== 'string' || value.trim() === '';
      });

      if (missingProofField) {
        alert(`Please provide ${missingProofField.label}.`);
        return;
      }
    }


    const autoGeneratedData: Record<string, any> = { ...formEntries };
    const schema = SHEET_CONFIGS[activeSheet] || [];
    schema.forEach(field => {
      if (field.autoGenerate) {
        switch (field.name) {
          case 'srNo':
            autoGeneratedData[field.name] = '';
            break;
          case 'timestamp':
            autoGeneratedData[field.name] = new Date().toLocaleString('en-GB');
            break;
          case 'studentName':
            if (user && user.type === 'student') {
              autoGeneratedData[field.name] = user.name;
            }
            break;
          case 'rollNumber':
            if (user && user.type === 'student') {
              autoGeneratedData[field.name] = user.rollNumber;
            }
            break;
          case 'phoneNumber':
            if (user && user.type === 'student') {
              autoGeneratedData[field.name] = user.phoneNumber;
            }
            break;
          case 'sheetName':
            autoGeneratedData[field.name] = activeSheet;
            break;
          case 'recordsAdded':
            autoGeneratedData[field.name] = 1;
            break;
        }
      }
    });

    setIsSubmitting(true);
    try {
      if (!period) {
        throw new Error("No reporting period selected.");
      }
      await postRowToSheet(activeSheet, autoGeneratedData, period);

      const logData = {
        srNo: '',
        timestamp: new Date().toLocaleString('en-GB'),
        studentName: role === 'student' ? (user as any).name || '' : 'Faculty',
        rollNumber: role === 'student' ? (user as any).rollNumber || '' : '0',
        phoneNumber: role === 'student' ? (user as any).phoneNumber || '' : '0',
        sheetName: activeSheet,
        recordsAdded: 1
      };
      await postRowToSheet("Student Submission Logs", logData, period);

      alert("Data submitted successfully!");
      (e.target as HTMLFormElement).reset();
    } catch (err) {
      const message = err instanceof Error ? err.message : "Direct submission error";
      alert(message);
    } finally {
      setIsSubmitting(false);
    }
  };

  if (!isAuthenticated) {
    return <LoginPage onLoginSuccess={() => {}} />;
  }

  const visibleSheets = getVisibleSheets();
  const schema = SHEET_CONFIGS[activeSheet] || [];
  const visibleSchema = schema.filter(field => !field.autoGenerate);
  const filteredSheets = visibleSheets.filter(s => s.toLowerCase().includes(searchQuery.toLowerCase()));

  const handleSheetSelect = (name: string) => {
    setActiveSheet(name);
    setIsSidebarOpen(false);
  };

  return (
    <div className="h-screen overflow-hidden bg-[#F9FBFA] text-slate-900 font-sans">
      <div className="relative flex h-full overflow-hidden">
        {isSidebarOpen && (
          <button
            className="fixed inset-0 z-30 bg-slate-900/35 backdrop-blur-[1px] lg:hidden"
            onClick={() => setIsSidebarOpen(false)}
            aria-label="Close sidebar overlay"
          />
        )}

        {/* SIDEBAR */}
        <aside className={`fixed inset-y-0 left-0 z-40 h-screen w-[85%] max-w-80 transform bg-white border-r border-mint-200 flex flex-col overflow-hidden shadow-2xl transition-transform duration-300 lg:static lg:z-20 lg:w-80 lg:max-w-none lg:translate-x-0 ${
          isSidebarOpen ? 'translate-x-0' : '-translate-x-full'
        }`}>
          <div className="flex items-start justify-between gap-4 p-5 sm:p-8 border-b border-mint-100 bg-white">
            <div>
              <div className="flex items-center gap-3 text-mint-700 mb-2">
                <LayoutDashboard size={22} className="bg-mint-600 p-1.5 rounded-lg text-white" />
                <span className="font-black uppercase tracking-tight text-lg sm:text-xl">Monthly Data Portal</span>
              </div>
              <p className="text-[10px] text-slate-400 font-black uppercase tracking-widest ml-1">
                {role === 'student' ? `Student: ${user && user.type === 'student' ? user.name : ''}` : 'Faculty Access'}
              </p>
            </div>
            <button
              className="lg:hidden rounded-xl p-2 text-slate-500 hover:bg-slate-100"
              onClick={() => setIsSidebarOpen(false)}
              aria-label="Close navigation"
            >
              <X size={18} />
            </button>

                  <div className="border-t border-mint-100 p-4">
                    <button
                      onClick={logout}
                      className="w-full flex items-center justify-center gap-2 bg-red-50 hover:bg-red-100 text-red-600 px-4 py-3 rounded-xl font-black text-sm transition-colors"
                    >
                      <LogOut size={16} /> Logout
                    </button>
                  </div>
          </div>

          <div className="p-5 sm:p-6">
            <div className="relative">
              <Search className="absolute left-4 top-3.5 text-slate-400" size={16} />
              <input
                type="text"
                placeholder="Search..."
                className="w-full bg-slate-50 border border-slate-200 rounded-2xl py-3 pl-12 pr-4 text-xs focus:ring-4 focus:ring-mint-500/10 focus:border-mint-500 outline-none text-slate-900 font-bold"
                onChange={(e: React.ChangeEvent<HTMLInputElement>) => setSearchQuery(e.target.value)}
              />
            </div>
          </div>

          <nav className="flex-1 overflow-y-auto overscroll-contain px-3 sm:px-4 pb-8 sm:pb-10 space-y-1">
            {filteredSheets.map((name, index) => {
              // If the name starts with a pattern like 5A, 5B, 5C, 12A, 12B, 12C, don't prepend index
              const isSubsection = /^\d{1,2}[A-C] /.test(name);
              return (
                <button
                  key={name}
                  onClick={() => handleSheetSelect(name)}
                  className={`w-full flex items-center justify-between px-4 sm:px-6 py-3.5 sm:py-4 rounded-2xl text-[10px] transition-all group ${
                    activeSheet === name ? 'bg-mint-600 text-white shadow-xl font-black translate-x-1' : 'text-slate-500 hover:bg-mint-50 hover:text-mint-700 font-bold'
                  }`}
                >
                  <span className="truncate uppercase tracking-tight text-left">{isSubsection ? name : `${index + 1}. ${name}`}</span>
                  <ChevronRight size={14} className={activeSheet === name ? 'opacity-100' : 'opacity-0 group-hover:opacity-100'} />
                </button>
              );
            })}
          </nav>
        </aside>

        {/* MAIN CONTENT */}
        <main className="min-w-0 flex-1 h-screen flex flex-col overflow-hidden bg-white">
          <header className="sticky top-0 z-10 bg-white/95 border-b border-mint-100 px-4 sm:px-6 lg:px-10 py-4 flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4 shadow-sm">
            <div className="flex items-start gap-3 sm:gap-4 min-w-0 w-full justify-between">
              <div className="flex items-center gap-3 min-w-0">
                <button
                  className="lg:hidden mt-0.5 rounded-xl border border-slate-200 p-2 text-slate-600 hover:bg-slate-50"
                  onClick={() => setIsSidebarOpen(true)}
                  aria-label="Open navigation"
                >
                  <Menu size={18} />
                </button>
                <h2 className="text-lg sm:text-2xl lg:text-3xl font-black text-slate-900 tracking-tight uppercase break-words">
                  Department of ECE, DTU
                </h2>
              </div>
              <div className="self-start sm:self-auto flex items-center gap-2 bg-slate-50 border border-slate-200 rounded-xl px-4 py-2.5 text-xs font-bold text-slate-700">
                <Calendar size={14} />
                <select
                  value={period || ''}
                  onChange={(e) => setPeriod(e.target.value as PeriodOption)}
                  className="bg-transparent border-none outline-none font-bold text-slate-700 cursor-pointer"
                >
                  {PERIOD_OPTIONS.map((opt) => (
                    <option key={opt} value={opt}>{opt}</option>
                  ))}
                </select>
              </div>
            </div>
          </header>

          <div className="flex-1 overflow-y-auto px-4 sm:px-6 lg:px-10 py-6 sm:py-8 lg:py-10 space-y-8 sm:space-y-9 lg:space-y-10">
            {/* Section Heading only */}
            <div className="mb-8">
              <h1 className="text-2xl sm:text-3xl lg:text-4xl font-black text-mint-700 tracking-tight mb-1">
                {activeSheet || "Section Name"}
              </h1>
            </div>
            <section className="bg-white border border-mint-100 rounded-3xl sm:rounded-[2rem] lg:rounded-[2.5rem] p-5 sm:p-8 lg:p-10 shadow-xl shadow-mint-100/10">
              <h3 className="text-[11px] sm:text-xs font-black uppercase tracking-[0.25em] sm:tracking-[0.3em] text-slate-400 mb-6 sm:mb-8 lg:mb-10 flex items-center gap-2">
                <Plus size={16} /> New Record
              </h3>
              {visibleSchema.length > 0 ? (
                <form onSubmit={appendToDf} className="grid grid-cols-1 md:grid-cols-2 gap-x-5 lg:gap-x-8 gap-y-4 sm:gap-y-5">
                  {visibleSchema.map(field => (
                      <div key={field.name} className={field.label.toLowerCase().includes('link') ? "md:col-span-2" : "md:col-span-1"}>
                        <label className="block text-sm sm:text-base font-black text-slate-800 uppercase tracking-[0.08em] mb-2 ml-0.5">
                          {field.label}
                        </label>
                        {field.options && field.options.length > 0 ? (
                          <select
                            name={field.name}
                            required
                            defaultValue=""
                            className="w-full bg-slate-50 border border-slate-200 rounded-xl px-3.5 sm:px-4 py-2.5 sm:py-3 text-base focus:bg-white focus:border-mint-500 focus:ring-4 focus:ring-mint-500/10 outline-none transition-all text-slate-900 font-semibold"
                          >
                            <option value="" disabled>Select</option>
                            {field.options.map(opt => (
                              <option key={opt} value={opt}>{opt}</option>
                            ))}
                          </select>
                        ) : (
                          <input
                            name={field.name}
                            type={field.type === 'url' ? 'text' : field.type}
                            inputMode={field.type === 'url' ? 'url' : undefined}
                            placeholder={field.type === 'url' ? 'e.g. link.com or https://link.com' : undefined}
                            required
                            className="w-full bg-slate-50 border border-slate-200 rounded-xl px-3.5 sm:px-4 py-2.5 sm:py-3 text-base focus:bg-white focus:border-mint-500 focus:ring-4 focus:ring-mint-500/10 outline-none transition-all text-slate-900 font-semibold"
                          />
                        )}
                      </div>
                    ))}
                  <div className="md:col-span-2 flex justify-stretch sm:justify-end mt-2 sm:mt-4">
                    <button
                      type="submit"
                      disabled={isSubmitting}
                      className="w-full sm:w-auto bg-mint-600 hover:bg-mint-700 disabled:bg-mint-300 text-white font-black uppercase tracking-widest px-8 py-4 rounded-xl transition-all flex items-center justify-center gap-3"
                    >
                      {isSubmitting ? (
                        <Loader2 size={18} className="animate-spin" />
                      ) : (
                        <Plus size={18} />
                      )}
                      Submit Record
                    </button>
                  </div>
                </form>
              ) : (
                <p className="text-center text-slate-500 font-semibold">Select a sheet from the sidebar to begin.</p>
              )}
            </section>

            {role === 'faculty' && studentLogs.length > 0 && (
              <section>
                <h3 className="text-xs font-black uppercase tracking-[0.3em] text-slate-400 mb-6 flex items-center gap-2">
                  <Layers size={16} /> Submission Log
                </h3>
                <div className="bg-white border border-mint-100 rounded-3xl shadow-xl shadow-mint-100/10 overflow-hidden">
                  <div className="overflow-x-auto">
                    <table className="w-full text-sm">
                      <thead className="bg-slate-50">
                        <tr>
                          {schema.map(field => (
                            <th key={field.name} className="px-6 py-4 font-black text-slate-500 uppercase tracking-wider text-xs text-left whitespace-nowrap">
                              {field.label}
                            </th>
                          ))}
                          <th className="px-6 py-4 font-black text-slate-500 uppercase tracking-wider text-xs text-left">Status</th>
                        </tr>
                      </thead>
                      <tbody className="divide-y divide-mint-100">
                        {studentLogs.map((row: any) => (
                          <tr key={row.id} className="hover:bg-mint-50/50 transition-colors">
                            {schema.map(field => (
                              <td key={field.name} className="px-6 py-4 whitespace-nowrap text-slate-700 font-medium max-w-xs truncate">
                                {String(row.data[field.name] ?? '')}
                              </td>
                            ))}
                            <td className="px-6 py-4 whitespace-nowrap">
                              {row.isSynced ? (
                                <span className="inline-flex items-center gap-1.5 bg-teal-100 text-teal-700 font-bold text-xs px-2.5 py-1 rounded-full">
                                  <Check size={14} /> Synced
                                </span>
                              ) : row.isSyncing ? (
                                <span className="inline-flex items-center gap-1.5 bg-sky-100 text-sky-700 font-bold text-xs px-2.5 py-1 rounded-full">
                                  <Loader2 size={14} className="animate-spin" /> Syncing...
                                </span>
                              ) : (
                                <span className="inline-flex items-center gap-1.5 bg-slate-100 text-slate-600 font-bold text-xs px-2.5 py-1 rounded-full">
                                  Not Synced
                                </span>
                              )}
                            </td>
                          </tr>
                        ))}
                      </tbody>
                    </table>
                  </div>
                </div>
              </section>
            )}
          </div>
        </main>
      </div>
    </div>
  );
}